version: '3.8'

services:
  # Redis for state management (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - distributed-net

  # Node 1
  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    container_name: dist-node-1
    environment:
      - NODE_ID=node-1
      - NODE_HOST=0.0.0.0
      - NODE_PORT=5000
      - NODE_CLUSTER_PORT=5001
      - CLUSTER_NODES=node-1:node1:5000,node-2:node2:5000,node-3:node3:5000
      - REDIS_HOST=redis
      - LOG_LEVEL=INFO
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - node1_data:/app/data
    networks:
      - distributed-net
    depends_on:
      - redis
    restart: unless-stopped

  # Node 2
  node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    container_name: dist-node-2
    environment:
      - NODE_ID=node-2
      - NODE_HOST=0.0.0.0
      - NODE_PORT=5000
      - NODE_CLUSTER_PORT=5001
      - CLUSTER_NODES=node-1:node1:5000,node-2:node2:5000,node-3:node3:5000
      - REDIS_HOST=redis
      - LOG_LEVEL=INFO
    ports:
      - "5010:5000"
      - "5011:5001"
    volumes:
      - node2_data:/app/data
    networks:
      - distributed-net
    depends_on:
      - redis
    restart: unless-stopped

  # Node 3
  node3:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    container_name: dist-node-3
    environment:
      - NODE_ID=node-3
      - NODE_HOST=0.0.0.0
      - NODE_PORT=5000
      - NODE_CLUSTER_PORT=5001
      - CLUSTER_NODES=node-1:node1:5000,node-2:node2:5000,node-3:node3:5000
      - REDIS_HOST=redis
      - LOG_LEVEL=INFO
    ports:
      - "5020:5000"
      - "5021:5001"
    volumes:
      - node3_data:/app/data
    networks:
      - distributed-net
    depends_on:
      - redis
    restart: unless-stopped

networks:
  distributed-net:
    driver: bridge

volumes:
  redis_data:
  node1_data:
  node2_data:
  node3_data:
