global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'distributed-sync-nodes'
    static_configs:
      - targets:
          - 'node1:5001'
          - 'node2:5001'
          - 'node3:5001'
        labels:
          group: 'distributed-cluster'

  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis:6379'
